# Generated by Django 4.0.1 on 2022-01-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0002_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
